#!/bin/bash

### BEGIN INIT INFO
# Provides:          JCatascopia-Server
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: JCatascopia-Server deamon
# Description:       JCatascopia Monitoring Server v0.2 init.d script
### END INIT INFO

# Author: Demetris Trihinas <trihinas@cs.ucy.ac.cy>

NAME=JCatascopia-Server
LOCKFILE=/var/lock/JCatascopia-Server-lock
JCPATH=/usr/local/bin/JCatascopiaServerDir

case $1 in
    start)
		if [ -e $LOCKFILE ] ; then
            echo "$NAME already up and running..."
    	    exit
        fi
        touch $LOCKFILE
        /bin/bash $JCPATH/JCatascopia-Server-start.sh
        echo "Starting $NAME..."
    ;;
    stop)
        if [ -e $LOCKFILE ] ; then
            rm -f $LOCKFILE
            echo "Stopping $NAME..."
            /bin/bash $JCPATH/JCatascopia-Server-stop.sh
        else  
	    	echo "$NAME not running..."
	    	exit
	    fi
    ;;
    restart)
    	if [ -e $LOCKFILE ]; then
    		rm -f $LOCKFILE
    	fi
		$0 stop
		$0 start
    ;;
    *)
    	echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
esac
exit
